name: boardgame
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  url_launcher: ^6.1.7
  flutter_svg: ^2.1.0
  feather_icons:
    path: ./patches/flutter_feather_icons
  supabase_flutter: ^2.8.4
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  crypto: ^3.0.7
  image_picker: ^1.2.3
  image: ^4.0.17
  just_audio: ^0.10.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/vector/
    - assets/logo/
    - assets/song.mp3
    - assets/background/
    - assets/character/
    - assets/character_sheet/
    - assets/eco_crisis_card/
    - assets/eco_crisis_card/Eco Crisis Card-Africa-Back/
    - assets/eco_crisis_card/Eco Crisis Card-Asia-Back/
    - assets/eco_crisis_card/Eco Crisis Card-Europe-Back/
    - assets/eco_crisis_card/Eco Crisis Card-North America-Back/
    - assets/eco_crisis_card/Eco Crisis Card-Central & South America-Back/
    - assets/action_card/
    - assets/token/
    - assets/Element Eco Avenger/Start page/
    - assets/Element Eco Avenger/Multiplayer page/
    - assets/Element Eco Avenger/Menu page/
    - assets/Element Eco Avenger/select char/
    - assets/Element Eco Avenger/map/
    - assets/Element Eco Avenger/boardgame_asset/

flutter_icons:
  android: true
  ios: true
  image_path: assets/token/Move Icon.png
